### ISSUE TITLE
LC Thermostats: Errors/Duplicates in timeline

### ISSUE THREAD

**Issue by Friedi1970** [mskg/homey-heating#68]
**Describe the bug**
I am using Danfoss thermostats and every time when the plan sets the temperature everything goes well but a couple of minutes later there is another try to set the temperature (what sometimes floods my timeline!).

The device itself get the value the first time, so there is no problem with heating but it is a bit annoying when you see the flooded timeline :(

Anotherthing which I realized today is the setting of a device which has been already deselected yesterday. No idea why the app try to set this device ...

**Screenshots**
Double set
![428d8cae-4bc4-40ab-a0d3-9b231d51d125](https://user-images.githubusercontent.com/47818803/53391494-cdac2780-3996-11e9-9e99-1029e7eaee9e.jpeg)

An error from a device which was already deselected
![36db11e6-0a86-4722-b2aa-c063d8f95849](https://user-images.githubusercontent.com/47818803/53390913-14008700-3995-11e9-9d6f-b52947f85835.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: IOS 12.1.4

**Comment by mskg** [comment]
Hi Marco, thanks for taking the time to make such a detailed report. According to you description

I rely on the driver's feedback that something has succeeded.

**Comment by mskg** [comment]
Hi Marco, thanks for taking the time to make such a detailed report, that realy helps. According to your description, there could be those problems:

1. A general problem with setting temperatures and associated reporting e.g. actions are executed multiple times, etc.
1. Problem with the driver of Danfos LC thermostats
1. Problem that a plan's changes have not been saved/applied

**1./2.** are closely related. For you to understand: I heavily rely on the Homeys feedback (which means drivers feedback), that setting a device's capability succeeded. When a driver reports a failure, I retry the action 5 times, while always doubeling the time between retries (exponential backoff). But, that retry and the reporting to the timeline are tight together: Only one final reporting for all retires. 

As devices can be part of many plans, I deduplicate the actions to set the `target_temperature` based on the internal identifier of the devices. If a device is part of many plans (at the same time), I resolve the temperature to the highest setpoint. Such, setting temperaturs twice should not happen at all.

My strongest guess: The driver probably reports something that I cannot work with, and we have to find out what that is. I checked the logfiles and this error matches your screenshots: https://sentry.io/share/issue/f66baf92180c48e58a5ce765c9ca6a7b/

I also checked the Danfoss driver for LC12/13 (https://github.com/athombv/com.danfoss) and they have a bugfix in the latest version that states `Fix a bug causing a timeout error in the smartphone app v2`. Could you please check your driver's version? Still I assume that you're already on it due to the autoupdates of Homey. 

**3.** Could you please verify that by opening that plan again in the settings area? Is the device removed there? Did you select zones? Is the device still shown in the "temperature-page"?

Last but not least. I need more detailed reporting to hunt that things. Can you please `Create [a] Diagnostics Report` that I can look at you're logfiles. I'm realy curious to see what that might be.

**Comment by mskg** [comment]
Are you able to submit a `Diagnostic Report`?

**Comment by Friedi1970** [comment]
Well, mainly it was my mistake :( I activated a zone where the room sensor was in it. but anyway, as soon as the RS is in it I get an error. The thing is that the value is not stored in the RS. I really don't have an idea why.
At the moment I excluded the room sensors. It is the Devolo room thermostat. It is a bit annoying but it works for now.

**Comment by mskg** [comment]
Can you please still probably include the sensor again and send the logs - I would like to see if there is a general problem?

**Comment by Friedi1970** [comment]
With logs you are talking about the Diagnostic Report? If not pls. describe how to get the log.
Of course I will do. I think it is a general problem. All of them in all rooms have the same problem and actually there is no connection problem.
Maybe I need time till Sunday.

**Comment by mskg** [comment]
Yes. If you click that button, I receive a detailed logfile of your Homey with respect to this App. 

The button is hidden at the same place where you can remove an App.

If you want to make it perfect for me:
1. Restart the App
2. Wait a minute 
3. Reproduce the problem 
4. Press the button 

Looking forward (somehow) :)

**Comment by Friedi1970** [comment]
Hi again,

I added the RS and restarted the app before I went sleeping. Hope this is also good for you?

The error:


Ans here is the code: 036f993b-c2d9-4206-b11d-bfe1cbb0ac7e

All the best,
Marco

**Comment by mskg** [comment]
I received the files and will check what happened.

**Comment by mskg** [comment]
Working on it. I can only guess what happens. Most likely, there is a problem with the driver for the LCs. They seem to fail, if the target_temperature is set to a value it already has. I will add a check and ask you to try.

**Comment by Friedi1970** [comment]
As soon as you ask for it I will try :)
