### ISSUE TITLE
Exceptions holiday and summer

### ISSUE THREAD

**Issue by Friedi1970** [mskg/homey-heating#70]
**Describe the bug**
I really don‘t know whether this is a bug or just a missing information.

**To Reproduce**
When you got to exceptions in a plan there are the exceptions „... you are on holiday?“ and „... it is summer?“.
How will the app realize whether I am on holiday or not? Where to define? Maybe I missed it but I can‘t see a holiday mode in Homey :(
What about summer? When is it? On June, 21st? If so, this could be too late for countries in the south. Even in Germany I am not used to use heaters in May.

**Expected behavior**
Clarification when it is summer and what is the holiday mode. How to set them?

**Comment by mskg** [comment]
## Overview
A plan is the normal schedule, but than what happens if I'm at home unplanned? I leave home unplanned? I go to sleep earlier? We're on holiday for a couple of days?

How to configure these things? Make plans for all of them? I thought that's too much work. In my usecase, that just means I put everything to cool-down, or to a comfortable coazy temperature.

I called these setpoints exceptions, and the events `mode` for the heating scheduler.

## Modes
The heating scheduler knows modes than can be set either
- using Flow: The action is called `Set heating mode`
- or using the settings page: Drop-down on `Overview` | `Change heating mode`

The modes: 
- **One day at home**
- **One day away from home**
- **Sleeping**

are rest every day at 00:00 to `Automatic`.

The modes: 
- **On holiday**
- **Out of season (it's summer)**

stay until you set the scheduler back to any other mode.

## Your questions
- *You go on Holiday?* Tell the scheduler by flipping the mode
<img width="269" src="https://homey-heating.mskg.app/assets/screens/plans.png">

- *You decide that the heating season is over?* Flip the mode, and you're done. No automation and it doesn't make sense imho

- *You want to detect if somebody is at home?*
<img width="269" alt="make it warm" src="https://user-images.githubusercontent.com/46903097/53412509-d2d69a00-39c9-11e9-87cc-577dbe986f59.PNG">

**Comment by mskg** [comment]
Are any questions left open?

**Comment by Friedi1970** [comment]
Sorry for answering late but I was sick and had no brains for homey :(
No questions :) Now I got it. I was just confused because I am new to homey and therefore I was searching for a "holiday mode" ...

THANK YOU!

**Comment by mskg** [comment]
Cool. I added a FAQ page 

https://github.com/mskg/homey-heating/blob/master/docs/pages/faq.md 

Feel free to comment / change any time.

**Comment by Friedi1970** [comment]
Hi again,
 
Now I figured out a problem regarding what you suggested and I have no solution :(
In my scenario I activate the plan only when a specific variable is set otherwise the plan is disabled. When I now enable the plan the temperature will be set indipendend whether the door is open or not.
 
Do you have any idea to solve this problem?
 
Regards
Marco
